ws:
  ip: '0.0.0.0'
  port: 11112
tcp: 
  ip: '0.0.0.0'
  port: 36365
controller: 'TestCubeUSB'
logging:
  file:
    loglevel: 'INFO'
    filename: 'gizmo.production.log'
  console:
    loglevel: 'INFO'