ws:
  ip: '0.0.0.0'
  port: 22222
tcp: 
  ip: '0.0.0.0'
  port: 8080
controller: 
  name: 'TestCubeUSB'
  schema: 'testcube_hw.json'
model:
  schema: 'testcube_ui.json'
logging:
  loglevel: 'INFO'
  filename: 'gizmo.log'
