tcp:
  ip: '127.0.0.1'
  port: 36364
ws:
  ip: '127.0.0.1'
  port: 11111
controller: 'TestCubeUSB'
logging:
  file:
    loglevel: 'USB'
    filename: 'gizmo.production.log'
  console:
    loglevel: 'USB'